import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");

function parseEnvFile(filePath) {
  if (!existsSync(filePath)) {
    return {};
  }

  const source = readFileSync(filePath, "utf8");
  const values = {};

  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const separator = line.indexOf("=");
    if (separator === -1) {
      continue;
    }

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

function asBoolean(value, fallback = false) {
  if (value == null || value === "") {
    return fallback;
  }

  return ["1", "true", "yes", "on"].includes(String(value).trim().toLowerCase());
}

function cleanSecret(value) {
  const raw = String(value || "").trim();
  if (!raw || raw.includes("REPLACE_WITH")) {
    return "";
  }

  return raw;
}

const exampleEnv = parseEnvFile(resolve(rootDir, ".env.example"));
const fileEnv = parseEnvFile(resolve(rootDir, ".env"));
const env = {
  ...exampleEnv,
  ...fileEnv,
  ...process.env
};

const pluginPath = resolve(rootDir, env.OPENCLAW_PLUGIN_PATH || "./plugins/hhba-openclaw");
const outputPath = resolve(rootDir, env.OPENCLAW_CONFIG_OUT || "./generated/openclaw.hhba.config.jsonc");
const defaultLimit = Math.max(1, Math.min(20, Number(env.HHBA_DEFAULT_LIMIT || 5)));

const config = {
  plugins: {
    enabled: true,
    load: {
      paths: [pluginPath]
    },
    entries: {
      "hhba-openclaw": {
        enabled: true,
        config: {
          baseUrl: env.HHBA_BASE_URL || "https://REPLACE_WITH_HHBA_PUBLIC_URL",
          apiToken: cleanSecret(env.HHBA_API_TOKEN),
          defaultLimit
        }
      }
    }
  },
  tools: {
    allow: ["hhba-openclaw"]
  }
};

function ensureChannels() {
  if (!config.channels) {
    config.channels = {};
  }

  return config.channels;
}

const feishuAppId = String(env.FEISHU_APP_ID || "").trim();
const feishuAppSecret = cleanSecret(env.FEISHU_APP_SECRET);
const feishuVerificationToken = cleanSecret(env.FEISHU_VERIFICATION_TOKEN);
const feishuEncryptKey = cleanSecret(env.FEISHU_ENCRYPT_KEY);
const feishuDomain = String(env.FEISHU_DOMAIN || env.LARK_DOMAIN || "").trim();
const feishuUseWebhookMode = String(env.FEISHU_CONNECTION_MODE || "").trim().toLowerCase() === "webhook";

if (feishuAppId && feishuAppSecret) {
  const channels = ensureChannels();
  const account = {
    appId: feishuAppId,
    appSecret: feishuAppSecret,
    name: String(env.FEISHU_ACCOUNT_NAME || "HHBA OpenClaw").trim(),
    typingIndicator: asBoolean(env.FEISHU_TYPING_INDICATOR, true),
    resolveSenderNames: asBoolean(env.FEISHU_RESOLVE_SENDER_NAMES, true)
  };

  if (feishuDomain) {
    account.domain = feishuDomain;
  }

  if (feishuUseWebhookMode) {
    if (feishuVerificationToken) {
      account.verificationToken = feishuVerificationToken;
    }
    if (feishuEncryptKey) {
      account.encryptKey = feishuEncryptKey;
    }
  }

  channels.feishu = {
    enabled: true,
    dmPolicy: String(env.FEISHU_DM_POLICY || "pairing").trim() || "pairing",
    accounts: {
      main: account
    }
  };

  if (String(env.FEISHU_REQUIRE_MENTION || "").trim()) {
    channels.feishu.groups = {
      "*": {
        requireMention: asBoolean(env.FEISHU_REQUIRE_MENTION, true)
      }
    };
  }
}

if (String(env.TELEGRAM_BOT_TOKEN || "").trim()) {
  const channels = ensureChannels();
  channels.telegram = {
    enabled: true,
    botToken: String(env.TELEGRAM_BOT_TOKEN || "").trim(),
    dmPolicy: env.TELEGRAM_DM_POLICY || "open",
    groups: {
      "*": {
        requireMention: asBoolean(env.TELEGRAM_REQUIRE_MENTION, false)
      }
    }
  };
}

if (config.channels && Object.keys(config.channels).length === 0) {
  delete config.channels;
}

const rendered = `// Generated by HHBA OpenClaw Starter\n${JSON.stringify(config, null, 2)}\n`;

if (checkOnly) {
  console.log("Starter config check passed.");
  console.log(`Plugin path: ${pluginPath}`);
  console.log(`Output path: ${outputPath}`);
  process.exit(0);
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, rendered, "utf8");

console.log(`Rendered OpenClaw config -> ${outputPath}`);
