import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");

function parseEnvFile(filePath) {
  if (!existsSync(filePath)) {
    return {};
  }

  const source = readFileSync(filePath, "utf8");
  const values = {};

  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const separator = line.indexOf("=");
    if (separator === -1) {
      continue;
    }

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

function asBoolean(value, fallback = false) {
  if (value == null || value === "") {
    return fallback;
  }

  return ["1", "true", "yes", "on"].includes(String(value).trim().toLowerCase());
}

function cleanSecret(value) {
  const raw = String(value || "").trim();
  if (!raw || raw.includes("REPLACE_WITH")) {
    return "";
  }

  return raw;
}

const exampleEnv = parseEnvFile(resolve(rootDir, ".env.example"));
const fileEnv = parseEnvFile(resolve(rootDir, ".env"));
const env = {
  ...exampleEnv,
  ...fileEnv,
  ...process.env
};

const pluginPath = resolve(rootDir, env.OPENCLAW_PLUGIN_PATH || "./plugins/hhba-openclaw");
const outputPath = resolve(rootDir, env.OPENCLAW_CONFIG_OUT || "./generated/openclaw.hhba.config.jsonc");
const defaultLimit = Math.max(1, Math.min(20, Number(env.HHBA_DEFAULT_LIMIT || 5)));

const config = {
  plugins: {
    enabled: true,
    load: {
      paths: [pluginPath]
    },
    entries: {
      "hhba-openclaw": {
        enabled: true,
        config: {
          baseUrl: env.HHBA_BASE_URL || "https://REPLACE_WITH_HHBA_PUBLIC_URL",
          apiToken: cleanSecret(env.HHBA_API_TOKEN),
          defaultLimit
        }
      }
    }
  },
  tools: {
    allow: ["hhba-openclaw"]
  }
};

if (String(env.TELEGRAM_BOT_TOKEN || "").trim()) {
  config.channels = {
    telegram: {
      enabled: true,
      botToken: String(env.TELEGRAM_BOT_TOKEN || "").trim(),
      dmPolicy: env.TELEGRAM_DM_POLICY || "open",
      groups: {
        "*": {
          requireMention: asBoolean(env.TELEGRAM_REQUIRE_MENTION, false)
        }
      }
    }
  };
}

const rendered = `// Generated by HHBA OpenClaw Starter\n${JSON.stringify(config, null, 2)}\n`;

if (checkOnly) {
  console.log("Starter config check passed.");
  console.log(`Plugin path: ${pluginPath}`);
  console.log(`Output path: ${outputPath}`);
  process.exit(0);
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, rendered, "utf8");

console.log(`Rendered OpenClaw config -> ${outputPath}`);
